### ISSUE TITLE
Does it need stringr as am Imports or Depends ?

### ISSUE THREAD

**Issue by eddelbuettel** [ericgiunta/Colossus#12]
When trying to build the Colossus package as a binary for [r2u](https://eddelbuettel.github.io/r2u) it fails on

```r
* installing *source* package ‘Colossus’ ...
** package ‘Colossus’ successfully unpacked and MD5 sums checked
** using staged installation
** preparing to configure package 'Colossus' ...
Error in loadNamespace(x) : there is no package called ‘stringr’
Calls: source_file ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: configuration failed for package ‘Colossus’
* removing ‘/.....local build setup here..../build/jammy/Colossus/debian/r-cran-colossus/usr/lib/R/site-library/Colossus’
```

Once I ensure `stringr` is present it works.   Maybe you need to promote it from Suggests: to Imports: ?

Feel free to close if you think this is at may end.  The builds are in a cleanroom and only see the explicitly referenced packages.

**Comment by ericgiunta** [comment]
It is one of several packages used by the configuration script and not Colossus itself, so listing it under Imports threw a warning that it was imported but not used. I'm looking into a CRAN approved way to either bypass the warning or remove the dependence. It will hopefully be resolved quickly and a patch can be uploaded to CRAN.

**Comment by eddelbuettel** [comment]
The 'fails to load when building' could be a quirk of my setup though I do nothing special.  It may be a local artifact so feel free to close --- the only 'call' that really matters is whether CRAN is happy.  So all good from my end.

**Comment by ericgiunta** [comment]
The functions that required these packages are now part of the main package, and are now listed as Imports.
